### ISSUE TITLE
运行bash runs/quadratic/run.sh出现错误AttributeError: 'DataParallel' object has no attribute 'encoder'

### ISSUE THREAD

**Issue by MrLee12138** [epfml/attention-cnn#4]
由于显卡驱动版本不高的原因，我安装的cuda版本为9.0，pytorch1.1.0，但是执行bash runs/quadratic/run.sh时会出现错误如下：
Traceback (most recent call last):
  File "train.py", line 656, in <module>
    main()
  File "train.py", line 201, in main
    plot_attention_positions_all_layers(model, 9, writer, epoch)
  File "/mnt/4T/lhy/attention-cnn-master/utils/plotting.py", line 101, in plot_attention_positions_all_layers
    for layer_idx in range(len(model.encoder.layer)):
  File "/mnt/4T/lhy/anaconda3/envs/ATTEN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'encoder'
该如何解决呢？谢谢

**Comment by MrLee12138** [comment]
在其他提问中找到答案了
